/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.ifmo.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the document_ service. Represents a row in the &quot;da_document_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.ifmo.service.model.impl.document_ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.ifmo.service.model.impl.document_Impl}.
 * </p>
 *
 * @author rei
 * @see document_
 * @see ru.ifmo.service.model.impl.document_Impl
 * @see ru.ifmo.service.model.impl.document_ModelImpl
 * @generated
 */
public interface document_Model extends BaseModel<document_>, GroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document_ model instance should use the {@link document_} interface instead.
	 */

	/**
	 * Returns the primary key of this document_.
	 *
	 * @return the primary key of this document_
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document_.
	 *
	 * @param primaryKey the primary key of this document_
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the document ID of this document_.
	 *
	 * @return the document ID of this document_
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document_.
	 *
	 * @param documentId the document ID of this document_
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the group ID of this document_.
	 *
	 * @return the group ID of this document_
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this document_.
	 *
	 * @param groupId the group ID of this document_
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this document_.
	 *
	 * @return the company ID of this document_
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this document_.
	 *
	 * @param companyId the company ID of this document_
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this document_.
	 *
	 * @return the user ID of this document_
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this document_.
	 *
	 * @param userId the user ID of this document_
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this document_.
	 *
	 * @return the user uuid of this document_
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this document_.
	 *
	 * @param userUuid the user uuid of this document_
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this document_.
	 *
	 * @return the user name of this document_
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this document_.
	 *
	 * @param userName the user name of this document_
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this document_.
	 *
	 * @return the create date of this document_
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this document_.
	 *
	 * @param createDate the create date of this document_
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document_.
	 *
	 * @return the modified date of this document_
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document_.
	 *
	 * @param modifiedDate the modified date of this document_
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this document_.
	 *
	 * @return the title of this document_
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this document_.
	 *
	 * @param title the title of this document_
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this document_.
	 *
	 * @return the description of this document_
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this document_.
	 *
	 * @param description the description of this document_
	 */
	public void setDescription(String description);

	/**
	 * Returns the dl document ID of this document_.
	 *
	 * @return the dl document ID of this document_
	 */
	public long getDlDocumentId();

	/**
	 * Sets the dl document ID of this document_.
	 *
	 * @param dlDocumentId the dl document ID of this document_
	 */
	public void setDlDocumentId(long dlDocumentId);

	/**
	 * Returns the status of this document_.
	 *
	 * @return the status of this document_
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this document_.
	 *
	 * @param status the status of this document_
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this document_.
	 *
	 * @return the status by user ID of this document_
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this document_.
	 *
	 * @param statusByUserId the status by user ID of this document_
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this document_.
	 *
	 * @return the status by user uuid of this document_
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this document_.
	 *
	 * @param statusByUserUuid the status by user uuid of this document_
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this document_.
	 *
	 * @return the status by user name of this document_
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this document_.
	 *
	 * @param statusByUserName the status by user name of this document_
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this document_.
	 *
	 * @return the status date of this document_
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this document_.
	 *
	 * @param statusDate the status date of this document_
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this document_ is approved.
	 *
	 * @return <code>true</code> if this document_ is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this document_ is denied.
	 *
	 * @return <code>true</code> if this document_ is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this document_ is a draft.
	 *
	 * @return <code>true</code> if this document_ is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this document_ is expired.
	 *
	 * @return <code>true</code> if this document_ is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this document_ is inactive.
	 *
	 * @return <code>true</code> if this document_ is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this document_ is incomplete.
	 *
	 * @return <code>true</code> if this document_ is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this document_ is pending.
	 *
	 * @return <code>true</code> if this document_ is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this document_ is scheduled.
	 *
	 * @return <code>true</code> if this document_ is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ru.ifmo.service.model.document_ document_);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ru.ifmo.service.model.document_> toCacheModel();

	@Override
	public ru.ifmo.service.model.document_ toEscapedModel();

	@Override
	public ru.ifmo.service.model.document_ toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}